### ISSUE TITLE
unable to contact setting server

### ISSUE THREAD

**Issue by yantraos** [KeithDHedger/LFSPkg#1]
Hi sir,
after install lightdm  while logged in i getting the error is (Unable to contact setting server could not connect connection refused)
![IMG_20201125_100153](https://user-images.githubusercontent.com/74947649/100337690-bd0e6280-2ffd-11eb-9cd0-b6eb30ccecc1.jpg)

**Comment by KeithDHedger** [comment]
Lfspkg is a package manager.
you should post this on the lightdm mail lists, nothing to do do with this repo.
please try to be more careful in the futre.
